data_path: ./data/debug_data.csv
model_path: ./generative_models/checkpoints/gan_mol_zinc_debug.pkl
molecules_path: ./geterative_models/results/generated_molecules_gan_debug.csv
bs: 2
lr_optim: 0.01
lr_discr: 0.001
epochs: 10
num_molecules: 2000
log_path: ./molgen_logs/debug
label_smoothing: True
label_smoothing_params: (0.0, 0.9)
num_gen_iterations: 3
reward_clamp: True
update_baseline_weights: (0.99, 0.01)
entropy_weight: 0.01 # раньше везде стоял 0.01
gen_clip_grad_value: 0.1 # раньше везде стоял 0.1
add_validity: True

# self.rnn = nn.LSTM(latent_dim, latent_dim, num_layers=2, batch_first=True)